# GitHub Actions workflow for building and testing Flask app
name: CI/CD Flask App

on: #Trigger whenever there is a push to my main or master branch
  push:
    branches: [main, master]

jobs: #The actions

  build: 
    runs-on: ubuntu-latest #Universal OS that is heavily supported by developers

    steps:
      - name: Checkout code #Cloning code to new computer
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

  test:
    needs: build #we need the build job to complete before we run out tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code #Cloning code to new computer
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Print debugging information
        run: |
          echo "Python Version: $(python --version)"
          echo "Working Directory: $(pwd)"
          echo "Contents of Working Directory: $(ls -l)"
          echo "Contents of site-packages: $(ls -l venv/lib/python*/site-packages)"

      - name: Run tests
        run: python -m unittest discover -s tests -p 'test_*.py' #Running all test files inside my test folder al long as the file starts with tests_(something).py
  # CI Completed